services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  CookiePal\CookiePalIntegration\:
    resource: '../Classes/*'

  CookiePal\CookiePalIntegration\Hooks\PageRenderer\TrackingCodeInjector:
    public: true
